name: PR Build and Tests

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: release
  test:
    uses: ./.github/workflows/e2e.yml
    needs: [build]
    with:
      artifact-id: ${{ needs.build.outputs.deb-artifact }}